### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by SdotVdot** [tsutterley/reference-toolkit#1]
It is not working with Python 3.8.5.
When I type:
python gen_citekeys.py --author=Rignot --year=2008 --doi="10.1038/ngeo102"
I get
Traceback (most recent call last):
  File "gen_citekeys.py", line 141, in <module>
    main()
  File "gen_citekeys.py", line 136, in main
    citekey = gen_citekey(A,Y,D,T)
  File "gen_citekeys.py", line 61, in gen_citekey
    author = author.decode('unicode-escape')
AttributeError: 'str' object has no attribute 'decode'

EDIT: If I change from
author.decode('unicode-escape')
to
author.encode().decode('unicode-escape')
it works...

**Comment by tsutterley** [comment]
hey @SdotVdot Thanks for stopping by.  I honestly didn't think anyone would ever look at these programs.  Updated the repo today which includes a fix for this.
